version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: containers/Dockerfile
    command: npm start 
    volumes:
      - .:/app
    ports:
      - "5050:5050"
  # test:
  #   image: node:14-alpine
  #   volumes:
  #     -./:app:cached

