FROM node:18
# Create app directory
WORKDIR /usr/src/app

RUN npm i -g nodemon
COPY package*.json ./
RUN npm install
# Copy in the source code
COPY . .

# Don't use root user
# USER node
EXPOSE 5050

CMD ["nodemon", "routecost.js"]